config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/projects',   to: 'static_pages#projects',   via: 'get'
  match '/research', to: 'static_pages#research', via: 'get'
  match '/publications', to: 'static_pages#publications', via: 'get'
  
 
  

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
    @images = Dir.glob("app/assets/images/index/*.jpg").sort_by {rand}
  end

  def about 
  end

  def contact
  end

  def projects
  end

  def research
  end

  def publications
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nemestudio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'nemestudio', madia: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'nemestudio_media', media: 'screen', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width" />
</head>
<body>
  <%= yield %>
    <script>
    $("#slideshow > div:gt(0)").hide();

    setInterval(function() { 
      $('#slideshow > div:first')
        .fadeOut(1000)
        .next()
        .fadeIn(1000)
        .end()
        .appendTo('#slideshow');
    },  4000);

    $(document).ready(function(){
      $("#hideShowDiv").hide();
      $("#show").click(function(){
        $("#hideShowDiv").slideDown();
      });
      $("#hide").click(function(){
        $("#hideShowDiv").slideUp();
      });
    });
</script>
</body>
</html>

app/views/news/news.html.erb
<%= render 'shared/nav' %>

app/views/shared/_dropdown.html.erb
<div id="hideShowDiv" class="dropdown">
<div id="text_frame">
<div class="about_paragraph">
<h1>NEMESTUDIO</h1>
<p>ulpario ea sediate cabore, vellabo. Voluptam quiduci usdaescipsa corere porrore mquam, tecte nima volessed quaerro ipidusdae volum ipsusapis reptasp idendaes modignate ipsam vitam soles explibus sitatumque qui qui as idestrum expe nam, se voloris nonsequae andae eossum facide
ulpario ea sediate cabore, vellabo.</p>
<p class="i">Voluptam quiduci usdaescipsa corere porrore mquam, tecte nima volessed quaerro ipidusdae volum ipsusapis reptasp idendaes modignate ipsam vitam soles explibus sitatumque qui qui as idestrum expe nam, se voloris nonsequae andae eossum facide</p></br>
<p>The studio welcomes expressions of interest, something, something, something.</p> </br>
<p>Download portfolio <%= link_to 'here', "assets/portfolio.pdf", :target => '_blank' %>.</p>
</div>
<div class="about_paragraph">
<h1>NeyranTuran</h1>
Neyran Turan is an architect, and currently an Assistant Professor at Rice University School of Architecture.Turan received her Bachelor of Architecture from Istanbul Technical University, holds a masters degree from Yale University School of Architecture</span> and a doctoral degree from Harvard University Graduate School of Design (GSD).
<p class="i">Turan’s work focuses on contemporary interpretation of scale, infrastructure and ecology, and their potentiality for new positionings in architecture and urbanism. She is the cofounder of NEMESTUDIO, a design and research collaborative.Turan is also the founding chief-editor of the recently launched Harvard GSD journal (volume 1: 2008, volume 2: Spring 2009).</p>
Turan’s recent publications include articles in Thresholds, ACSA Surfacing Urbanisms, Bidoun- Technology, Corporations-Cities, and upcoming book chapters in Landscapes of Development (Harvard University), the Superlative City: Dubai and the Urban Condition in the EarlyTwenty- First Century (Harvard University) and Public#6: DenseCity.Turan has also acted as the assistant editor for the book,Joseph Lluis Sert: The Architect of Urban Design (with Hashim Sarkis and Eric Mumford,Yale University Press, 2008).</p>
<p class="i">Before coming to Rice,Turan was teaching at Harvard GSD. She
also taught at Yale University School of Architecture, Boston Architecture College, and Istanbul Technical University.Turan is currently working on the forthcoming volume of the New Geographiesjournal titled After Zero.</p>
</div>
<div class="about_paragraph">
<h1>Mete Sonmez</h1>
<p>
Mete holds a Master of Architecture degree from Harvard University Graduate School of Design and obtained his Bachelor of Architecture degree
from IstanbulTechnical University. He gained experience and recognition through his experience as design lead on various projects at H.S.A.L.U.D. with Hashim Sarkis and at M.S.A. with Jorge Silvetti and Rodolfo Machado, both internationally renowned architectural practices based in Boston.</p>
<p class="i">
Mete is an award-winning designer with over 15 years extensive national and international experience. He has taught design studios and is a guest critic and lecturer at schools such as Harvard University, Rice University, Istanbul Technical University, Boston Architecture College and the University of Houston.
</p>
</div>
<div class="about_paragraph">
<h1>Contact</h1>
<p>
1510 Harold St </br>
HoustonTX</br> 
77006</br>
USA</br>
</p>
<p class="margin">
+1 (713) 489-2133</br>
</p>
<p class="margin">
<%= mail_to "info@nemestudio.com" %></br> 
<%= mail_to "metesonmez@nemestudio.com" %></br> 
<%= mail_to "neyranturan@nemestudio.comIlis" %>
</p>
<button id="hide"><%= image_tag('exit_button.png', alt: "close") %></button>
</div>
</div>
</div>

app/views/shared/_header.html.erb
<header id='header'>
<%= image_tag('nemelogo.png', alt: "nemestudio", id: 'show') %>
</header>

app/views/shared/_nav.html.erb
	<nav>
		<ul>
			<li><%= link_to "Projects", projects_path %></li>
			<li><%= link_to "Publications", publications_path %></li>
			<li><%= link_to "Research", research_path %></li>
		</ul>
		<ul>
			<li><%= link_to "About", about_path %> </li>
			<li>News</li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>

app/views/static_pages/about.html.erb
<div id="dropdown">
<%= link_to "X", about_path, id: "close_dropdown" %>
	<div id="dropdown_txt">
		So much <br />
		Text about these architects ...
	</div>
</div>
<%= link_to 'About', '#', id: 'showHideLink' %>

<%= render 'shared/header' %>
<%= render 'shared/nav' %>


<div class='body_container'>
	<p>
	This is the about page. It may function as a dropdown or be a seperate page depending on how the site develops. 
	</p>
</div>

app/views/static_pages/contact.html.erb
<%= render 'shared/nav' %>

app/views/static_pages/index.html.erb
<%= render 'shared/dropdown' %>

<%= render 'shared/header' %>

	<div id="slideshow">
	 <% @images.each do |image| %>
	 	<div>
   		<%= image_tag "index/#{image.split('/').last}" %>
   		</div>
 	 <% end %>
    </div>

app/views/static_pages/projects.html.erb
<%= render 'shared/nav' %>

app/views/static_pages/publications.html.erb
<%= render 'shared/nav' %>

app/views/static_pages/research.html.erb
<%= render 'shared/nav' %>